/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ContainerSizeValues } from "@alexbjr369/hive-common";
export namespace Components {
    interface HvContainer {
        /**
          * Defines the component size.
         */
        "size"?: ContainerSizeValues;
    }
}
declare global {
    interface HTMLHvContainerElement extends Components.HvContainer, HTMLStencilElement {
    }
    var HTMLHvContainerElement: {
        prototype: HTMLHvContainerElement;
        new (): HTMLHvContainerElement;
    };
    interface HTMLElementTagNameMap {
        "hv-container": HTMLHvContainerElement;
    }
}
declare namespace LocalJSX {
    interface HvContainer {
        /**
          * Defines the component size.
         */
        "size"?: ContainerSizeValues;
    }
    interface IntrinsicElements {
        "hv-container": HvContainer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hv-container": LocalJSX.HvContainer & JSXBase.HTMLAttributes<HTMLHvContainerElement>;
        }
    }
}
